# Generated by Django 2.0.5 on 2018-08-31 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('Industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Industry', verbose_name='行业')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='sub_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.SubIndustry', verbose_name='细分行业'),
        ),
    ]
