# Generated by Django 2.0.5 on 2018-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180831_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='ordernum',
            field=models.SmallIntegerField(default=1, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='subindustry',
            name='ordernum',
            field=models.SmallIntegerField(default=1, verbose_name='序号'),
        ),
    ]
