# Generated by Django 2.0.5 on 2018-09-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180831_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Downloads',
            field=models.IntegerField(default=0, verbose_name='下载量'),
        ),
        migrations.AddField(
            model_name='data',
            name='pageviews',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
