# Generated by Django 2.0.5 on 2018-09-01 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180901_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='ordernum',
            field=models.SmallIntegerField(default=1, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='datatype',
            name='ordernum',
            field=models.SmallIntegerField(default=1, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='data',
            name='sub_industry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.SubIndustry', verbose_name='细分行业'),
        ),
    ]
