# Generated by Django 2.0.5 on 2018-09-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180901_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='uid',
            field=models.CharField(default=3, max_length=10, unique=True, verbose_name='唯一标识'),
        ),
    ]
