# Generated by Django 2.0.5 on 2018-09-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_data_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='uid',
            field=models.CharField(default=0, max_length=10, verbose_name='简写'),
        ),
    ]
