# Generated by Django 2.0.5 on 2018-09-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_industry_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='uid',
            field=models.CharField(max_length=10, unique=True, verbose_name='简写'),
        ),
    ]
