# Generated by Django 2.0.5 on 2018-09-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180901_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='addr',
            field=models.FileField(blank=True, null=True, upload_to='datas/', verbose_name='文件地址'),
        ),
    ]
