# Generated by Django 2.0.5 on 2018-09-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20180901_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_source',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.DataSource', verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.DataType', verbose_name='数据形式'),
        ),
        migrations.AlterField(
            model_name='data',
            name='industry',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.Industry', verbose_name='行业类型'),
        ),
    ]
