# Generated by Django 2.0.5 on 2018-09-01 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20180901_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sub_industry',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.SubIndustry', verbose_name='细分行业'),
        ),
    ]
