# Generated by Django 2.0.5 on 2018-09-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180902_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.DataSource', verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.DataType', verbose_name='数据形式'),
        ),
        migrations.AlterField(
            model_name='data',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Industry', verbose_name='行业类型'),
        ),
        migrations.AlterField(
            model_name='data',
            name='sub_industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.SubIndustry', verbose_name='细分行业'),
        ),
    ]
