# Generated by Django 2.0.5 on 2018-09-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20180902_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': '数据资源表', 'verbose_name_plural': '数据资源表'},
        ),
        migrations.AlterIndexTogether(
            name='data',
            index_together={('name', 'create_time', 'uid')},
        ),
    ]
