# Generated by Django 2.0.5 on 2018-09-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20180902_1405'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='web_data',
        ),
    ]
