# Generated by Django 2.0.5 on 2018-09-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20180902_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(upload_to='datas/', verbose_name='文件地址'),
        ),
        migrations.AlterField(
            model_name='data',
            name='head',
            field=models.FileField(blank=True, default='heads/head1.jpg', null=True, upload_to='heads/', verbose_name='文件头图'),
        ),
    ]
