# Generated by Django 2.0.5 on 2018-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20180902_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='desc',
            field=models.CharField(default='数据描述', max_length=512, verbose_name='数据描述'),
        ),
    ]
