# Generated by Django 2.0.5 on 2018-09-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_data_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
    ]
