# Generated by Django 2.0.5 on 2018-09-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_remove_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='years',
            field=models.SmallIntegerField(choices=[(1, '古代'), (2, '近代'), (3, '现代')], default=3, verbose_name='数据年份'),
        ),
    ]
