# Generated by Django 2.0.5 on 2018-09-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_data_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='姓名')),
                ('email', models.EmailField(max_length=128, null=True, unique=True, verbose_name='邮箱地址')),
                ('corp', models.CharField(max_length=255, verbose_name='公司名')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('needs', models.TextField(max_length=8000, verbose_name='需求')),
                ('memo', models.TextField(max_length=5120, null=True, verbose_name='备注')),
            ],
        ),
    ]
