# Generated by Django 2.0.5 on 2018-09-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='memo',
            field=models.TextField(blank=True, max_length=5120, null=True, verbose_name='备注'),
        ),
    ]
