# Generated by Django 2.0.5 on 2018-09-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20180903_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='memo',
            field=models.TextField(default='备注', max_length=5120, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_source',
            field=models.ForeignKey(blank=True, default=8, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.DataSource', verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.DataType', verbose_name='数据形式'),
        ),
        migrations.AlterField(
            model_name='data',
            name='head',
            field=models.FileField(default='heads/head1.jpg', upload_to='heads/', verbose_name='文件头图'),
        ),
        migrations.AlterField(
            model_name='data',
            name='industry',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.Industry', verbose_name='行业类型'),
        ),
        migrations.AlterField(
            model_name='data',
            name='sub_industry',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.SubIndustry', verbose_name='细分行业'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.UserInfo', verbose_name='用户名'),
        ),
    ]
