# Generated by Django 2.0.5 on 2018-09-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20180903_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior',
            name='page',
            field=models.CharField(default='index', max_length=64, verbose_name='浏览页面'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='times',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
