# Generated by Django 2.0.5 on 2018-09-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20180903_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='memo',
            field=models.TextField(blank=True, default='备注', max_length=5120, null=True, verbose_name='备注'),
        ),
    ]
