# Generated by Django 2.0.5 on 2018-09-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20180904_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbehavior',
            name='page',
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='industry',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.Industry', verbose_name='浏览行业'),
        ),
    ]
