# Generated by Django 2.0.5 on 2018-09-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20180904_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='size',
            field=models.SmallIntegerField(choices=[(1, 'KB'), (2, 'MB'), (3, 'GB')], default=1, verbose_name='数据规格'),
        ),
    ]
