# Generated by Django 2.0.5 on 2018-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_data_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='needs',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='需求'),
        ),
    ]
