# Generated by Django 2.0.5 on 2018-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20180905_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='corp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='公司名'),
        ),
    ]
