# Generated by Django 2.0.5 on 2018-09-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20180905_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='corp',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='公司名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(max_length=56, verbose_name='姓名'),
        ),
    ]
